print("========================================")
print("             EXPENSE TRACKER")
print("       Know where your money goes.")
print("========================================")
print()
print("MAIN MENU")
print("[1] Add an expense         (coming soon)")
print("[2] View all expenses      (coming soon)")
print("[3] Show total spent       (coming soon)")
print("[4] Exit                   (coming soon)")
print()

name = input("What's your name? ")
print(f"Welcome, {name}! Let's log two expenses.")